"""
1D-CNN action classification model trainer for Dynamic Director AI.

Trains a lightweight Depthwise Separable 1D-CNN on the synthetic skeleton
time-series data generated by generate_synthetic_data.py.

Architecture:
  Input [30, 27] → Conv1D → DepthwiseSeparableConv1D → GAP → Dense → Softmax(6)

The trained model is exported to TFLite format (INT8 and FP16 quantization)
for deployment on Android via PoseTimeSeriesBuffer + ActionClassifier pipeline.

Usage:
  1. First generate data: python generate_synthetic_data.py
  2. Then train:          python train_action_model.py
  3. Deploy:              Copy action_model_int8.tflite to app/src/main/assets/
"""

import os
import sys
import numpy as np

try:
    import tensorflow as tf
    from tensorflow import keras
    from tensorflow.keras import layers
except ImportError:
    print("TensorFlow is required. Install with: pip install tensorflow")
    sys.exit(1)

# Constants
NUM_FRAMES = 30
FEATURE_DIM = 27  # 9 keypoints × 3 (x, y, confidence)
NUM_CLASSES = 6   # None, Banzai, Pointing, Waving, Throwing, Clapping
ACTION_NAMES = ["None", "Banzai", "Pointing", "Waving", "Throwing", "Clapping"]

DATA_DIR = "data"
MODEL_DIR = "models"


def load_data():
    """Load the synthetic dataset generated by generate_synthetic_data.py."""
    X_train = np.load(os.path.join(DATA_DIR, "X_train.npy"))
    y_train = np.load(os.path.join(DATA_DIR, "y_train.npy"))
    X_val = np.load(os.path.join(DATA_DIR, "X_val.npy"))
    y_val = np.load(os.path.join(DATA_DIR, "y_val.npy"))
    X_test = np.load(os.path.join(DATA_DIR, "X_test.npy"))
    y_test = np.load(os.path.join(DATA_DIR, "y_test.npy"))
    
    print(f"Train: {X_train.shape}, Val: {X_val.shape}, Test: {X_test.shape}")
    return X_train, y_train, X_val, y_val, X_test, y_test


def build_model():
    """
    Build a lightweight Depthwise Separable 1D-CNN for action classification.
    
    Architecture designed for mobile inference:
    - Small parameter count (~20K params)
    - TFLite-compatible operations only
    - Global Average Pooling eliminates FC layers
    - Dropout for regularization
    
    Expected inference time on mid-range phone: < 3ms
    """
    inputs = keras.Input(shape=(NUM_FRAMES, FEATURE_DIM), name="skeleton_input")
    
    # Block 1: Standard Conv1D for initial feature extraction
    x = layers.Conv1D(32, kernel_size=3, padding="same", activation="relu", name="conv1d_1")(inputs)
    x = layers.BatchNormalization(name="bn_1")(x)
    
    # Block 2: Depthwise Separable Conv1D (lightweight but effective)
    x = layers.SeparableConv1D(64, kernel_size=3, padding="same", activation="relu", name="sep_conv1d_1")(x)
    x = layers.BatchNormalization(name="bn_2")(x)
    
    # Block 3: Another Separable Conv with increased receptive field
    x = layers.SeparableConv1D(64, kernel_size=5, padding="same", activation="relu", name="sep_conv1d_2")(x)
    x = layers.BatchNormalization(name="bn_3")(x)
    
    # Global Average Pooling (collapses time dimension → [batch, 64])
    x = layers.GlobalAveragePooling1D(name="gap")(x)
    
    # Classifier head
    x = layers.Dense(32, activation="relu", name="dense_1")(x)
    x = layers.Dropout(0.2, name="dropout")(x)
    outputs = layers.Dense(NUM_CLASSES, activation="softmax", name="action_output")(x)
    
    model = keras.Model(inputs=inputs, outputs=outputs, name="action_classifier_1d_cnn")
    return model


def train(model, X_train, y_train, X_val, y_val, epochs=50, batch_size=32):
    """Train the model with early stopping and learning rate reduction."""
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=0.001),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )
    
    callbacks = [
        keras.callbacks.EarlyStopping(
            monitor="val_accuracy",
            patience=10,
            restore_best_weights=True,
            verbose=1
        ),
        keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss",
            factor=0.5,
            patience=5,
            min_lr=1e-6,
            verbose=1
        ),
    ]
    
    history = model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=epochs,
        batch_size=batch_size,
        callbacks=callbacks,
        verbose=1
    )
    
    return history


def evaluate(model, X_test, y_test):
    """Evaluate the model and print per-class metrics."""
    print("\n=== Test Set Evaluation ===")
    loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
    print(f"Test Loss: {loss:.4f}")
    print(f"Test Accuracy: {accuracy:.4f}")
    
    # Per-class accuracy
    predictions = model.predict(X_test, verbose=0)
    pred_classes = np.argmax(predictions, axis=1)
    
    print("\nPer-class accuracy:")
    for cls in range(NUM_CLASSES):
        mask = y_test == cls
        if mask.sum() > 0:
            cls_acc = (pred_classes[mask] == cls).mean()
            print(f"  {ACTION_NAMES[cls]:12s}: {cls_acc:.4f} ({mask.sum()} samples)")
    
    # Confusion matrix
    print("\nConfusion Matrix:")
    print(f"{'':>12s}", end="")
    for name in ACTION_NAMES:
        print(f"{name:>10s}", end="")
    print()
    
    for true_cls in range(NUM_CLASSES):
        print(f"{ACTION_NAMES[true_cls]:>12s}", end="")
        mask = y_test == true_cls
        for pred_cls in range(NUM_CLASSES):
            count = ((pred_classes[mask]) == pred_cls).sum()
            print(f"{count:>10d}", end="")
        print()
    
    return accuracy


def export_tflite(model, output_dir):
    """Export the model to TFLite format with INT8 and FP16 quantization."""
    os.makedirs(output_dir, exist_ok=True)
    
    # Save Keras model first
    keras_path = os.path.join(output_dir, "action_classifier.keras")
    model.save(keras_path)
    print(f"\nKeras model saved: {keras_path}")
    
    # FP16 quantization
    converter_fp16 = tf.lite.TFLiteConverter.from_keras_model(model)
    converter_fp16.optimizations = [tf.lite.Optimize.DEFAULT]
    converter_fp16.target_spec.supported_types = [tf.float16]
    tflite_fp16 = converter_fp16.convert()
    
    fp16_path = os.path.join(output_dir, "action_model_fp16.tflite")
    with open(fp16_path, "wb") as f:
        f.write(tflite_fp16)
    print(f"FP16 TFLite model: {fp16_path} ({len(tflite_fp16)} bytes)")
    
    # INT8 quantization (requires representative dataset)
    X_train = np.load(os.path.join(DATA_DIR, "X_train.npy"))
    
    def representative_dataset():
        for i in range(min(200, len(X_train))):
            yield [X_train[i:i+1].astype(np.float32)]
    
    converter_int8 = tf.lite.TFLiteConverter.from_keras_model(model)
    converter_int8.optimizations = [tf.lite.Optimize.DEFAULT]
    converter_int8.representative_dataset = representative_dataset
    converter_int8.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter_int8.inference_input_type = tf.float32  # Keep float I/O for easier integration
    converter_int8.inference_output_type = tf.float32
    
    try:
        tflite_int8 = converter_int8.convert()
        int8_path = os.path.join(output_dir, "action_model_int8.tflite")
        with open(int8_path, "wb") as f:
            f.write(tflite_int8)
        print(f"INT8 TFLite model: {int8_path} ({len(tflite_int8)} bytes)")
    except Exception as e:
        print(f"INT8 quantization failed (expected on some setups): {e}")
    
    print(f"\nTo deploy on Android, copy the .tflite file to:")
    print(f"  app/src/main/assets/action_model.tflite")


def main():
    print("=" * 60)
    print("Dynamic Director AI - 1D-CNN Action Classifier Training")
    print("=" * 60)
    
    # Check if data exists
    if not os.path.exists(os.path.join(DATA_DIR, "X_train.npy")):
        print(f"\nData not found in '{DATA_DIR}/'. Generating synthetic data first...")
        from generate_synthetic_data import generate_dataset
        generate_dataset(samples_per_class=500, output_dir=DATA_DIR)
    
    # Load data
    X_train, y_train, X_val, y_val, X_test, y_test = load_data()
    
    # Build model
    model = build_model()
    model.summary()
    
    # Train
    print("\n--- Training ---")
    history = train(model, X_train, y_train, X_val, y_val, epochs=50, batch_size=32)
    
    # Evaluate
    accuracy = evaluate(model, X_test, y_test)
    
    # Export to TFLite
    print("\n--- Exporting to TFLite ---")
    export_tflite(model, MODEL_DIR)
    
    print(f"\n{'=' * 60}")
    print(f"Training complete! Final test accuracy: {accuracy:.4f}")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    main()
