package com.example.director

import android.graphics.Bitmap

/**
 * A rule set generated by analyzing a reference image.
 * This represents the "ideal composition" we want to capture.
 */
data class CompositionRule(
    val targetAction: String?,       // e.g. "Banzai", "Clapping"
    val requiresSmile: Boolean,      // Should the subject be smiling?
    val faceTargetRegion: String?    // e.g. "Center", "RuleOfThirds_TopLeft"
)

/**
 * Directs the photography by matching real-time AI results against
 * an ideal composition rule extracted from a reference image using a VLM.
 */
class ReferenceDirector {

    // In a real implementation, this would be generated by Gemini VLM.
    // We use a mock rule for the POC.
    private var currentRule: CompositionRule? = null

    /**
     * Set an ideal reference image. A Vision-Language Model (like Gemini)
     * would analyze this image to extract the composition intent.
     */
    fun setReferenceImage(bitmap: Bitmap) {
        // MOCK: Gemini VLM Analysis
        // Prompt: "Analyze this photo and extract composition parameters: what is the main action, is the subject smiling, and where is the face located?"
        currentRule = CompositionRule(
            targetAction = "Waving",
            requiresSmile = true,
            faceTargetRegion = "Center"
        )
    }

    fun clearReference() {
        currentRule = null
    }

    val isActive: Boolean
        get() = currentRule != null

    /**
     * Calculate how closely the current real-time AI results match the reference composition.
     * Returns a score from 0.0 to 1.0.
     */
    fun calculateMatchScore(face: FaceResult?, pose: PoseResult?): Float {
        val rule = currentRule ?: return 0f
        
        var score = 0f
        var maxScore = 0f

        // 1. Action Matching
        if (rule.targetAction != null) {
            maxScore += 1.0f
            if (pose != null && pose.actionName == rule.targetAction) {
                // Weight the match by the confidence of the pose detection
                score += (1.0f * pose.confidence)
            }
        }

        // 2. Expression Matching
        if (rule.requiresSmile) {
            maxScore += 1.0f
            if (face != null) {
                score += face.smilingProbability
            }
        }

        // 3. Face Region Matching (Simplified for POC)
        if (rule.faceTargetRegion != null) {
            maxScore += 1.0f
            if (face != null) {
                // If a face is detected, we give a partial score for now.
                // In a full implementation, we would compare the bounding box
                // normalized coordinates against the target region.
                score += 0.8f 
            }
        }

        if (maxScore == 0f) return 0f
        
        return score / maxScore
    }
}
